### ISSUE TITLE
Require full name for new accounts 

### ISSUE THREAD

**Issue by DutcherNL** [esrg-knights/Squire#111]
Account names currently ask a nickname for the first name instead of one's regular name. This creates issues in site behaviour elsewhere. It's best to ask peoples actual names when creating a new account instead (and have nicknames stored elsewhere).

Note: Yes, this means that for accounts with memberships their name is stored twice but this is better than unclarity who an account belongs to.

**Comment by mrbazzan** [comment]
Should i give this issue a try?

**Comment by EricTRL** [comment]
Closed in #160
