### ISSUE TITLE
Add Knights documents to the site

### ISSUE THREAD

**Issue by DutcherNL** [esrg-knights/Squire#155]
Add the Statuten, HR and Privacy guidelines to the app for download.

(obviously as local files, no need to add them to github)

**Comment by EricTRL** [comment]
Do we really need them on the app as well? They're currently already available at https://kotkt.nl/downloads/

**Comment by DutcherNL** [comment]
O yeah, huh. Nvm. I hadnd't noticed the download page on the main site XD
