### ISSUE TITLE
Selected headers in the settingstab are a bit dark.

### ISSUE THREAD

**Issue by LenaWil** [esrg-knights/Squire#178]
![Screenshot 2021-11-20 at 16-39-43  Squire Account ](https://user-images.githubusercontent.com/6208937/142732335-a5a70b13-531c-4879-b89b-e504a2621651.png)

I thought it was supposed to be that dark the first time, but now I realise it's probably not intended.

**Comment by LenaWil** [comment]
![Screenshot_20211124-194819](https://user-images.githubusercontent.com/6208937/143297070-35ef1d7e-50aa-43ea-9205-8eb949deab3f.jpg)

Calendar headers are also the wrong colour.

**Comment by EricTRL** [comment]
I've gone ahead and merged this issue with #179 as they're both related to the dark mode. Might be easier to track stuff if it's all in a single issue 😄
