### ISSUE TITLE
Dark Theme Styling Problems

### ISSUE THREAD

**Issue by Ndoll1** [esrg-knights/Squire#179]
Dark theme fonts hebben op meerdere plekken te weinig contrast ten opzichte van de achtergrond. Hierdoor zijn ze slecht leesbaar.

**Comment by Ndoll1** [comment]
Kan worden opgelost door bepaalde CSS aspecten vast te gaan zetten aan de thema's zelf

Voorpagina

- [ ] Achtergrond van groepen lijst
- [ ] Kleur van bug report knop
- [ ] Kleur font bij "datum" van activiteit
- [ ] Kleur font van header

**Comment by EricTRL** [comment]
- [ ] Header tabs on settings & committees page
- [ ] Calendar list month/week headers
