### ISSUE TITLE
Mobile? dark theme had white background

### ISSUE THREAD

**Issue by LenaWil** [esrg-knights/Squire#183]
![Screenshot_20211123-001658](https://user-images.githubusercontent.com/6208937/142949387-464190c8-3608-4e78-afd3-3666c08a9b09.jpg)

Just putting it here so I don't forget and can look at it tomorrow.

**Comment by Ndoll1** [comment]
Hard refresh and it has been fixed

Ctrl + shift + R

**Comment by LenaWil** [comment]
I don't have a control button on the keyboard of my phone, but that was indeed the issue. Thanks.
