### ISSUE TITLE
Inventory Export

### ISSUE THREAD

**Issue by EricTRL** [esrg-knights/Squire#217]
Not only is the inventory useful for members to see what we actually own, it is also useful for the board to estimate how costly the stuff is we actually own.

Things to add:
- [ ] Export functionality for inventory items (just like it is currently done for the membership file)
- [ ] An `estimated_price`-column for inventory items, so the export can be used to estimate the total value of our inventory.

**Comment by DutcherNL** [comment]
Both inventory export and inventory item are introduced in the above PR
