### ISSUE TITLE
Activities that have been edited by the organizer show up double when importing to (Google) calendar

### ISSUE THREAD

**Issue by TimHeiszwolf** [esrg-knights/Squire#263]
When you importing the Knights activity calendar into your (Google) calendar activities that have been edited by an organizer show up twice. Once as the "base" activity (as it was created in the admin panel) and once as edited by the organizer.
<img width="660" alt="2022-03-11_01 14 24_firefox" src="https://user-images.githubusercontent.com/32781879/157777496-6bb621bb-0b72-4f05-be5b-b59e69eb2369.png">
<img width="683" alt="2022-03-11_01 14 27_firefox" src="https://user-images.githubusercontent.com/32781879/157777530-50844e19-6ab3-470f-bd52-cad4b9511350.png">

**Comment by DutcherNL** [comment]
This is a duplicate as described in #213 and is aware with us

(thanks for still reporting it @TimHeiszwolf, but I will close to keep our administration clean :))
