### ISSUE TITLE
settings do not define AUTH_USER_CLASS

### ISSUE THREAD

**Issue by DutcherNL** [esrg-knights/Squire#66]
Right now locally all references to users in code are replaced with the ExtendedUser proxy model. This makes maintaining code annoying and also requires a lot of arguably dubious user.__class__ = ExtendedUser when retrieving User from request (which is not the ExtendedUser.

It's better to make a non-proxy CustomUser(AbstractUser) class. However, this requires some rewriting in the database as this would break all currently automated intemediate model names.

**Comment by DutcherNL** [comment]
See here: https://docs.djangoproject.com/en/3.1/ref/settings/#auth-user-model

It should not be adjusted after deployment, though the current implementation, I believe, will only become worse as we add more features, so we need to address this soon.

**Comment by EricTRL** [comment]
`ExtendedUser` no longer exists as of #177, I don't think this is needed anymore?
