### ISSUE TITLE
Show claimants on achievements for registered members

### ISSUE THREAD

**Issue by ReneKOTKT** [esrg-knights/Squire#71]
The bottom of the page mentions this, but this does not seem possible

**Comment by EricTRL** [comment]
René dit is een gevalletje van "slechte UI en hoe Squire nu gebruikt wordt." Squire heeft een ledenbestand dat nu niet wordt gebruikt. Volgens Squire ben je alleen lid als je daarin staat (op een bepaalde manier), wat voor de meeste daadwerkelijke leden niet het geval is.

**Comment by EricTRL** [comment]
Note that logged in users are not necessarily members.
Squire offers membership-file functionality, but this is currently not used. (PR #69 fixes the last few issues that were there which prevented us from actually using it.)

This means that people who are actually members IRL are not (always) members in Squire (as they don't have a member-entry in Squire itself).
