### ISSUE TITLE
Link ActivitySlots to an ActivityMoment instead of an Activity (with a recurrence_id)

### ISSUE THREAD

**Issue by DutcherNL** [esrg-knights/Squire#83]
_Edit: Initial statement refers to recurrence_id in activityslots_

We are not using it in the front view,
We are not using it in the admin view
We are not using it in activities
We are not using it in permissities

It serves no use but cluttering
It doesn't do a single thing

I don't know about you lot
But I'd like it gone from every slot

**Comment by KnightsSecret** [comment]
Yes please, this was my initial request for this:

- Make the time field not mandatory for a activity slot
Meaning that if you make a activity slot for a certain activity that by leaving the time fields empty the slot just copies the times from the parent activity. Cause now the time isn't even shown on the knights member-end but I still have to manually fil it in every time I create a slot even though I don't want it to differ at all.
For clarifation, i meant here the cases in the back-end create a slot like:
![image](https://user-images.githubusercontent.com/72865919/95988228-e2b62280-0e28-11eb-9d43-83976eea35e5.png)

**Comment by helaan** [comment]
While we can now have multiple of the same recurring activities on the same time, I don't think we will use this feature soon if ever. However this may be more difficult as the full datetime is used in the foreign key from ActivitySlot to Activity.

I think this highlights an issue in the design of the recurring activity model: To make it easier to change single occurrences of activities I suggest dropping the recurrency model altogether in favor of template activities with an associated recurrence which can be instantiated when someone joins or edits this activity. This also allows updating templates, as changes will then only take effect on future activities. What do you think?

**Comment by helaan** [comment]
What I just suggested will be a rigorous change but would also fix #85

**Comment by EricTRL** [comment]
>  To make it easier to change single occurrences of activities I suggest dropping the recurrency model altogether in favor of template activities with an associated recurrence which can be instantiated when someone joins or edits this activity.

Wouter and I already briefly discussed this earlier this week and ended up with a similar (if not the exact same) conclusion. 
During that same discussion, Wouter mentioned that he'd like to work on it so I'm leaving it up to him (unless he pings me :P)

**Comment by DutcherNL** [comment]
I have already implemented a feature in my local work that allows single activities to have adjusted settings which are also represented in the calendar (even the Google Calendar). Still got to write the related test cases though. But that PR is coming soon

**Comment by EricTRL** [comment]
Single occurrence editing has been made easier for a while since #96 , so this possibly isn't needed anymore.
We can still link slots to auto-created ActivityMoments (which represent a single occurrence) so we get rid of the entire recurrence_id field. Parent_activity would then change to parent_activity_moment.

Leaving the model as is, but getting rid of the time-part (and leaving in the date-part) requires way more work and doesn't really achieve anything other than not allowing recurrences on the same date anymore. That being said, I don't think that is what was being suggested here.

**Comment by DutcherNL** [comment]
It's a bit of data cleaning. Data-technical it can be read that slots can occur on different times than the activity, which isn't the case. It can also happen that there are slots which do not belong to an activity_moment (recurrent or not) which can be confusing.

Instead of the combination activity and recurrence_id we can just link to an activity_moment. Upon creation of a slot we can initiate the activitymoment instantly at the same time if it didn't exist yet. It also allows us to link slots for when certain activities are cancelled more easily and will prevent any lose slots somehow lingering in the database. The only downside that can occur is the very minimal race condition where two people are the first to create a slot at the same time and it will create a duplicate. These kind of race conditions are very rare in my experience. It happened, to my knowledge, once on the dining app (with a last entry on the dining list)
