### ISSUE TITLE
feature/1 divergent activity from recurring activity

### ISSUE THREAD

**Issue by KnightsSecret** [esrg-knights/Squire#85]
Hi all,
I have a few requests to make my work as secretary easier:

- Make it possible to have 1 activity from a recurring activity with different information, like e.q. location or maximum amount of members or starting time without having to exclude this activity in the recurring parent activity and making a new activity with the divergent information
(Cause know I just edit the recurring activity to match the current info, but that gives rise to confusion for members who aren't sure if for instance the BSA of 2 weeks was in Atlas as it stated last week, or is in Luna as it shows now)
I see two possible option in this, 
1) have a button which immediately copies the parent recurring activity info into a new activity when you exclude a specific date (or maybe with a button next to the excluding rule 'Do you want to make an new activity on this date based on this parent activity). This however really clutters the activities list overview, but this is fixed when there is a semi-permanent (standard on, but able to switch off) filter in the activities list for "(re)current or future activities" (which i would like anyway)
2) Make the exclude rule broader in which you can say "exclude this date, for only <>" with <> possibly being the location or the maximum amount of members or the starting time. And than having the option to fill in the <> with the information for that specific date only
If you guys see any other option that i'm missing, be free to use them in the case that it actually improves ánd the overview ánd the amount of actions I need to take in the current situation

**Comment by EricTRL** [comment]
Closed in #96
