### ISSUE TITLE
feature/Filter lists of activity (slots)

### ISSUE THREAD

**Issue by KnightsSecret** [esrg-knights/Squire#86]
Hi all,
I have a few requests to make my work as secretary easier:

- Have a semi-permanent (standard on, but able to switch off) filter in the activities list for "(re)current or future <>" with <> either activities or activity slots
Now it rapidly becomes a cluttering mess of activity (slots)

**Comment by helaan** [comment]
Can we add a button in the admin panel for an activity to list the slots for that activity?

**Comment by KnightsSecret** [comment]
I'm not sure what you suggest Helaan, but it's not gonna solve my problem. Cause if I now open the activity slot list i see this (without touching any filtering/sorting buttons)
![image](https://user-images.githubusercontent.com/72865919/95993301-3deb1380-0e2f-11eb-99ec-6041ab0c1544.png)
And if i do use the for instance sort on date button, it will not provide me with a useful sorting, cause non-recurring activities are not assigned a date and therefore i cannot properly sort on date. 
So searching for a LFG slot for today, the 14th, is still within the mess of either varies names to be sorted on (owners, parent activity or slot name where for instance "players' is quite non-distinctive there) and/or requires me to scroll relativly quite for, which is not user friendly. 

But if I would have a button that only shows the activities (Slots) with date today or in the future so many would disappear cause most are either recurring activities with not yet future slots or past time activities

**Comment by helaan** [comment]
For non-recurring activities you can filter or sort by activity, while for recurring activities you can sort by date.

Maybe we should take this discussion back to the beginning: what do you want to do? If doing this over text is not useful we can also do this via phone

**Comment by KnightsSecret** [comment]
Simple, i want to have the option to only see limited slots so i can easily find the one i need to adjust. Like just now a non-member canceled his attendance, for that i need to find the activity slot and then remove this person. If i don't have to first actively search for that slot, that makes this taks quite a lot easier. ( sorting on date doesn't work cause non-recurring activities are not shown there, sorting on parent activity and sorting on name doesn't really work cause those are not you know standardised or something and still leaves me searching for in this case "looking for group", sorting on owner is just entiryly not usefull in this case)

Second addition; the current sorting options are not resetablle unless you remove the added ?o=4.5 of the url. This is niet onoverkoombaar, maar ook niet echt prettig/ideaal werkend

**Comment by DutcherNL** [comment]
Just a small heads up: In a future update (currently in the master, just not live on the site) slots created in the front end will ALWAYS have a date assigned to them. Recurring or not. It made no sense to specifically write code to deal with omitted values.

**Comment by helaan** [comment]
> Can we add a button in the admin panel for an activity to list the slots for that activity?

Hmm, this wouldn't work nicely because of recurrent activities (see #83 ) but could be an option if that is adressed

**Comment by KnightsSecret** [comment]
And non recurring activities made in the back-end Dutcher? Cause otherwise it won't really change my point. 

Furthermore it just is easier to look for the right one when you only need to look in like a short list of like 6 entries (The upcoming 2 activities non-reccuring and the 4 recurrings (BSA, ORA, IW swordfight, OC) than in one with 40...

**Comment by DutcherNL** [comment]
I am actively trying to devellop the front end to be able to do all that should be expected to be needed on a regular basis. That includes creating and/or editing slots. I am not there yet, but it's getting there. Till then... the back-end is a viable option

**Comment by DutcherNL** [comment]
I believe this issue has been fixed for a while since #96  . So I'll close it until someone believes this is still an issue.
