### ISSUE TITLE
Feature/ Have an added part in Squire where the (webview of the) newsletters is stored

### ISSUE THREAD

**Issue by KnightsSecret** [esrg-knights/Squire#88]
Hi all,
I am using mailchimp to make a good looking newsletter with html. To mail this to all Knights, I sent myself an test newsletter from mailchimp, cope the html part (via inspect) then open an email in gmail, type something, inspect it, then edit that in html and paste the html into there, go back to the gmail mail and add all the emails in the bcc. 
In the base html I remove the additional footer and adds of mailchimp from the html. However there's one part i cannot remove/change and that is that the "view this email in browser" refers to a link like https://us2.campaign-archive.com/?e=__test_email__&u=757c1b68fdf99de784d26b551&id=76cd315816 which not only has "test email" in it, but is also an very ugly link.
Isn't it possible that, when i have the html base of the newsletter, I can add this to the webapp (maybe behind a login since stuff in the newsletter does contain personal names and sometimes foto's)? Than I can use that link in the send out Newsletter ánd the storage and thus looking up for people is improved.
(Also than we can just have an easy link to "here are all our past newsletters". So if people recall they saw something they can think he, maybe it was in there and look it up themseleves)

I have no clue to what extend this is possible, but I would love to have something like this. Even if it means I have to change how I send the newsletter ;p

**Comment by EricTRL** [comment]
@DutcherNL I reckon that the newsletter archive can be embedded into #287 once that goes live. Thoughts?

**Comment by DutcherNL** [comment]
I agree. Newsletters have already been removed from the headers in that PR
